version: '3.9'

services:
  pythonapp:
    container_name: pythonapp
    image: zeeshanib/webapp-docker:v2
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
       db:
        condition: service_healthy 

  
  db:
    container_name: db
    image: postgres:12
    ports:
        - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
# Set health checks to wait until postgres has started

    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"

    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}