apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp

    spec:
      containers:
      - name: webapp
        image: zeeshanib/webapp-docker:v0.0.2
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: DATABASE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      
  


  
