name: check

on:
  push:
    branches:
      - "main"
      - "ZeeshanIB-patch"
  pull_request:
    branches:
        - "main"
        - "ZeeshanIB-patch"
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.outputs.version }}

    steps:
    - name: Set the value
      run: |
        version=v.1.1.1
        echo "version=$version" >> $GITHUB_ENV
        echo "version=$version" >> $GITHUB_OUTPUT


  job2:
    runs-on: ubuntu-latest
   

    steps:
    - name: Use the value
      run: |
        echo ${{needs.job1.outputs.output1}}

      
    