name: check

on:
  push:
    branches:
      - "main"
      - "ZeeshanIB-patch"
  #pull_request:
   # branches:
    #    - "main"
     #   - "ZeeshanIB-patch"
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.version_print.outputs.version }}
     
    steps:
      - name: version_print
        run: echo "version=hello" >> $GITHUB_OUTPUT
      
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} 