name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Postgres service
      run: |
        sudo apt-cache policy postgresql
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-client
        sudo service postgresql start
        psql -c "CREATE DATABASE myapp_db;" -U postgres

    - name: Set up environment variables for webapp container
      run: echo "DATABASE_URL=postgres://postgres@localhost/myapp_db" >> $GITHUB_ENV





    - name: Build and run webapp container
      run: |
        docker run -p 3000:3000 -e DATABASE_URL -d ${{secrets.DOCKER_USER}}/webapp-docker:v2
