name: Deploy to Minikube

on: push
defaults:
  run:
    working-directory: ./K8S_config
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Minikube
      uses: medyagh/setup-minikube@master
    - name: Start Minikube
      run: minikube start
    - name: Install xdg-utils
      run: sudo apt-get install xdg-utils

    - name: Deploy
      run:  |
        kubectl apply -f secrets-config.yaml
        kubectl apply -f postgres-configmap.yaml
        kubectl apply -f postgres-statefulset.yaml
        kubectl apply -f flaskapp-deployment.yaml
        sleep 100 
        kubectl get pod
        kubectl get service
        kubectl get pvc
    - name: service
    
      run: |

        URL=$(minikube service webapp-service --url)
        echo "Service URL: $URL" 
        curl -X POST $URL/items -H "Content-Type: application/json" -d '{ "title":"helling", "content":"heling"}'
    # This command is for Ubuntu or Debian based Linux distributions. You may need to replace this command for other operating systems.
