name: Deploy to Minikube

on: push
defaults:
  run:
    working-directory: ./K8S_config
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Minikube
      uses: medyagh/setup-minikube@master
    - name: Start Minikube
      run: minikube start
    - name: Install xdg-utils
      run: sudo apt-get install xdg-utils

    - name: Deploy
      run:  |
        kubectl apply -f secrets-config.yaml
        kubectl apply -f postgres-configmap.yaml
        kubectl apply -f PVC-PV-deployment.yaml
        kubectl apply -f flaskapp-deployment.yaml
    - name: service
      run: minikube service webapp-service
      #minikube dashboard
