name: docker1
on:
  push:
  pull_request:
  workflow_dispatch:
  #repository_dispatch:
jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/reusable_build.yml
    with: 
      name: myapp
