name: pipeline
on:
  pull_request:
  
  workflow_dispatch:
     inputs:
      image_name:
        description: Name of the Docker image
        required: true
        type: string
        default: "webapp-docker"
      image_tag:
        description: Tag of the Docker image
        required: true
        type: string
        default: "v2"
  


defaults:
 run:
  working-directory: ./web-app
jobs:
  call-pyhthonapp_pipeline:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/pythonapp_pipeline.yml
    with:
      
      image_name: webapp-docker
      image_tag: v2
    secrets: inherit
  job2:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/pythonapp_pipeline.yml
    with:
      
      image_name: ${{ inputs.image_name }}
      image_tag: ${{ inputs.image_name }}
    secrets: inherit
