name: pipeline
on:
  workflow_dispatch:
     inputs:
      image_name:
        description: Name of the Docker image
        required: true
        type: string
        default: "webapp-dock"
      image_tag:
        description: Tag of the Docker image
        required: true
        type: string
        default: "v"
defaults:
 run:
  working-directory: ./web-app
jobs:
  call-pyhthonapp_pipeline:

    uses: ./.github/workflows/pythonapp_pipeline.yml
   
    secrets: inherit