name: pipeline
on:
  workflow_dispatch:
     inputs:
      image_name:
        description: Name of the Docker image
        required: true
        type: string
        default: "webapp-docker"
      image_tag:
        description: Tag of the Docker image
        required: true
        type: string
        default: "v2"


defaults:
 run:
  working-directory: ./web-app
jobs:
  call-pyhthonapp_pipeline:
    uses: ./.github/workflows/pythonapp_pipeline.yml
    with:
      
      image_name: webapp-docker
      image_tag: v2
      secrets: inherit