name: web-app pipeline

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: Name of the Docker image
        required: true
        type: string
        default: "webapp-docker"
      image_tag:
        description: Tag of the Docker image
        required: true
        type: string
        default: "v1"

env:
  IMAGE_NAME: ${{ inputs.image_name }}
  IMAGE_TAG: ${{ inputs.image_tag }}
  
# setting woking directory in github repo
defaults:
 run:
  working-directory: ./web-app
    
jobs:
  build-webapp-image:
    runs-on: ubuntu-22.04


    steps:
    - uses: actions/checkout@v3


    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - name: echo inputs
      run: |
        echo ${{ inputs.image_name }}:${{ inputs.image_tag }}
    - name: Build the Docker image
      
      run: |
        
        docker build --tag ${{secrets.DOCKER_USER}}/${{ inputs.image_name }}:${{ inputs.image_tag }} .
    - name: Docker Push to docker hub
      run: docker push ${{secrets.DOCKER_USER}}/${{ inputs.image_name }}:${{ inputs.image_tag }}



    - name: Start Web App container
      run: docker run -d --name webapp -p 80:80 ${{secrets.DOCKER_USER}}/${{ inputs.image_name }}:${{ inputs.image_tag }}


    
    - name: webapp container logs
      run: |
        docker logs webapp

 
    - name: running container

      run: |
        sleep 30
        docker ps
         


    - name: sending post requst
      run: |
        sleep 30
        curl -X POST http://localhost:80/items -H "Content-Type: application/json" -d '{"title": "title3", "content": "content3"}'

        curl -X GET http://localhost:80/items/1


