name: docker reusable workflow
on:
  push:
  #pull_request:
  workflow_call:
    #inputs:
    # DOCKER_USER:
    #   required: true
    #   type: string
    #  DOCKER_PASSWORD:
    #    required: true
    #    type: string
    
   # branches:
    #  - main
  #pull_request:
   # branches:
   #   - main
defaults:
 run:
  working-directory: ./web-app
    
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3


    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - name: Build the Docker image
      run: docker build --tag zeeshanib/webapp-docker:v2 .
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/webapp-docker:v2



  #  - name: Start Web App container
  #    run: docker run -d --name webapp --link postgres:postgres -e DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres -p 80:80 ${{secrets.DOCKER_USER}}/webapp-docker:v2
  #  - name: docker container list
  #    run: docker ps 
    

    


    - name: docker compose up
      run: docker-compose up -d

    - name: docker networks
      run: docker inspect db --format='{{ json .NetworkSettings.Networks }}' | jq && docker inspect pythonapp --format='{{ json .NetworkSettings.Networks }}' | jq

    - name: docker container list
      run: docker ps 
    - name: docker webapp logs
      run: docker logs pythonapp
    - name: exec
      run: docker exec -it pythonapp ping 172.18.0.3
    - name: curl_post
      run: |
        sleep 30
        curl -X GET http://172.18.0.3:80


