name: docker reusable workflow
on:
  push:
  pull_request:
  workflow_call:
    #inputs:
    # DOCKER_USER:
    #   required: true
    #   type: string
    #  DOCKER_PASSWORD:
    #    required: true
    #    type: string
    
   # branches:
    #  - main
  #pull_request:
   # branches:
   #   - main
defaults:
 run:
  working-directory: ./web-app
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - name: Build the Docker image
      run: docker build --tag zeeshanib/webapp-docker:v2 .
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/webapp-docker:v2


    - name: Start Postgres container
      run: docker run -d --name db -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=postgres -p 5432:5432 postgres:12

    - name: Start Web App container
      run: docker run -d --name webapp --link db:db -e DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres -p 80:80 ${{secrets.DOCKER_USER}}/webapp-docker:v2
    - name: docker container list
      run: docker ps 
    - name: curl_post
      run: |
        docker exec webapp sh -c 'apt-get update && apt-get install curl -y && curl -X POST http://localhost:80/items -H "Content-Type:application/json" -d '{"title":"title2", "content":"content2"}''


