name: docker reusable workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: docker login
      #env:
       #   DOCKER_USER: ${{secrets.DOCKER_USER}}
        #  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build . --file web-app-docker/Dockerfile --tag zeeshanib/webapp-docker:v2
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/webapp-docker:v2
  link:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start Postgres container
      run: docker run -d --name postgres -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 postgres:15-alpine

    - name: Start Web App container
      run: docker run -d --name webapp --link postgres:postgres -p 8000:8000 ${{secrets.DOCKER_USER}}/webapp-docker:v2
